import { StyleSheet } from 'react-native'


// Global Styles
export const globalStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    scrollView: {
      flex: 1,
      paddingLeft: 20,
      paddingRight: 20,
      paddingTop: 10
    },
    flatList: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: '#666',
    },
    centerContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    authContainer: {
      padding: 20,
      justifyContent: 'center',
      minHeight: '100%',
    },
    logo: {
      alignSelf: 'center',
      marginBottom: 20,
    },
    header: {
      marginBottom: 12
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 4,
    },
    headerSubtitle: {
      fontSize: 16,
      color: '#666',
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 8,
      color: '#333',
    },
    subtitle: {
      fontSize: 16,
      textAlign: 'center',
      color: '#666',
      marginBottom: 24,
    },
    inputContainer: {
      marginBottom: 16,
    },
    label: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 8,
      color: '#333',
    },
    sublabel: {
      fontSize: 14,
      color: '#676',
      marginBottom: 12,
    },
    input: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
    },
    primaryButton: {
      backgroundColor: '#E91E63',
      padding: 16,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 16,
    },
    primaryButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    primaryButtonDisabled: {
      backgroundColor: '#ddd',
    },
    secondaryButton: {
      padding: 16,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 8,
    },
    secondaryButtonText: {
      color: '#E91E63',
      fontSize: 16,
      fontWeight: '600',
    },
    outlineButton: {
      marginTop: 16,
      borderWidth: 2,
      borderColor: '#E91E63',
      padding: 16,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
      marginRight: 8,
    },
    outlineButtonText: {
      color: '#E91E63',
      fontSize: 16,
      fontWeight: '600',
    },
    card: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    cardIcon: {
      marginRight: 16,
    },
    cardContent: {
      flex: 1,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#333',
      marginBottom: 4,
    },
    cardDescription: {
      fontSize: 14,
      color: '#666',
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 12,
      color: '#333',
    },
    chipContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    chip: {
      backgroundColor: '#f5f5f5',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: '#ddd',
    },
    chipActive: {
      backgroundColor: '#E91E63',
      borderColor: '#E91E63',
    },
    chipText: {
      fontSize: 14,
      color: '#333',
    },
    chipTextActive: {
      color: '#fff',
    },
    timeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f5f5f5',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: '#ddd',
      gap: 6,
    },
    timeChipText: {
      fontSize: 14,
      color: '#333',
      fontWeight: '500',
    },
    preferenceButton: {
      backgroundColor: '#f5f5f5',
      padding: 16,
      borderRadius: 8,
      alignItems: 'center',
    },
    preferenceButtonText: {
      color: '#E91E63',
      fontSize: 16,
      fontWeight: '600',
    },
    itineraryCard: {
      backgroundColor: '#f9f9f9',
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: '#E91E63',
    },
    itineraryTime: {
      fontSize: 14,
      fontWeight: '600',
      color: '#E91E63',
      marginBottom: 4,
    },
    itineraryTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#333',
      marginBottom: 4,
    },
    itineraryDescription: {
      fontSize: 14,
      color: '#666',
      marginBottom: 8,
    },
    itineraryCost: {
      fontSize: 14,
      fontWeight: '600',
      color: '#4CAF50',
    },
    costBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    costText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#4CAF50',
      marginLeft: 4,
    },
    buttonRow: {
      flexDirection: 'row',
      marginTop: 0,
      marginBottom: 16
    },
    // Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 24,
      width: '100%',
      maxWidth: 400,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
    },
    closeButton: {
      padding: 4,
      cursor: 'pointer',
    },
    modalMessage: {
      fontSize: 16,
      color: '#666',
      marginBottom: 24,
      lineHeight: 24,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
    },
    modalCancelButton: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
      backgroundColor: '#f5f5f5',
      cursor: 'pointer',
    },
    modalCancelText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#666',
    },
    modalConfirmButton: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
      backgroundColor: '#E91E63',
      cursor: 'pointer',
    },
    modalConfirmText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#fff',
    },
    map: {
      width: '100%',
      height: '100%',
    },
    calendarButton: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: '#4CAF50',
      padding: 4,
      margin: 4,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    calendarButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    shareButton: {
      flex: 1,
      flexDirection: 'row',
      borderWidth: 2,
      borderColor: '#E91E63',
      padding: 2,
      margin: 4,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    shareButtonText: {
      color: '#E91E63',
      fontSize: 16,
      fontWeight: '600',
      padding:10
    },
    locationBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#E8F5E9',
      padding: 12,
      borderRadius: 8,
      marginBottom: 24,
      gap: 8,
    },
    locationText: {
      fontSize: 14,
      color: '#4CAF50',
      fontWeight: '500',
    },
    locationBannerError: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFEBEE',
      padding: 12,
      borderRadius: 8,
      marginBottom: 24,
      gap: 8,
    },
    locationTextError: {
      fontSize: 14,
      color: '#f44336',
      fontWeight: '500',
    },
    infoBanner: {
      backgroundColor: '#FFF0F5',
      padding: 16,
      borderRadius: 8,
      marginBottom: 24,
    },
    infoText: {
      fontSize: 14,
      color: '#E91E63',
      textAlign: 'center',
      lineHeight: 20,
    },
  });